export const actionTypes = {
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  USER_EXISTS: "USER_EXISTS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  LOGOUT_USER: "LOGOUT_USER",
};
